# Inference from cricket dataset

In [1]:
import numpy as np

## Reading dataset

In [3]:
!head cric_data.tsv

	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216


## Loading dataset

In [2]:
cric_data = np.loadtxt("cric_data.tsv",skiprows=1)

### Sachin , Rahul and India will be the order of result

## 1. Find mean median and IQR for Sachin, Rahul and India

In [5]:
mean = np.mean(cric_data[:,1:],axis=0)
print(mean)

[ 39.87555556  32.06222222 220.79555556]


In [6]:
median = np.median(cric_data[:,1:],axis=0)
print(median)

[ 27.  22. 216.]


In [8]:
np.percentile?

In [9]:
quartiles = np.percentile(cric_data[:,1:],[25,75],axis=0)


In [10]:
quartiles

array([[  6.,   7., 175.],
       [ 63.,  53., 273.]])

In [11]:
iqr = np.diff(quartiles,axis=0)
print(iqr)

[[57. 46. 98.]]


## 2. Find the histogram of Sachin's scores with 10 bins

In [12]:
sachin_scores = cric_data[:,1]

In [13]:
np.histogram(sachin_scores,bins =10)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

## 3. Find mean of Sachin's scores grouped by 25 matches

In [17]:
sachin_25 = sachin_scores.reshape(9,25)

In [18]:
print(np.mean(sachin_25,axis=1))

[33.96 49.4  38.48 40.16 39.36 38.2  44.6  39.52 35.2 ]


## Find mean of Sachin's scores where he has a score of century

In [55]:
sachin_index_scores = cric_data[:,0:2]

In [57]:
indices = sachin_index_scores[sachin_scores >=100]

In [66]:
for i in indices[:,0] :
    e = int(i)
    print(e,np.sum(sachin_scores[0:e+1])/denom[e])

0 100.0
4 58.8
22 35.17391304347826
30 38.32258064516129
37 39.578947368421055
44 40.355555555555554
47 41.8125
56 40.228070175438596
57 41.60344827586207
64 41.261538461538464
68 40.57971014492754
94 40.810526315789474
115 39.310344827586206
116 40.01709401709402
134 39.32592592592592
148 39.93288590604027
159 40.40625
166 40.92215568862275
175 41.01136363636363
177 41.30337078651685
181 41.42857142857143
182 42.0
204 40.72195121951219
208 40.70334928229665
210 40.96208530805687
221 40.112612612612615


In [67]:
print(indices[:,0].shape)

(26,)


In [19]:
rahul_scores = cric_data[:,2]

In [20]:
np.mean(sachin_scores[sachin_scores>=100])

125.0

In [33]:
for i in range(10,101,10):
    print(i,np.mean(sachin_scores[(rahul_scores<i) & (rahul_scores>i-10)]))

10 41.906976744186046
20 54.333333333333336
30 31.17391304347826
40 42.88235294117647
50 45.36363636363637
60 28.714285714285715
70 27.076923076923077
80 36.57142857142857
90 34.0
100 63.5


In [31]:
for i in range(10,101,10):
    print(i,np.mean(rahul_scores[(sachin_scores<i) & (sachin_scores>i-10)]))

10 38.81818181818182
20 39.24
30 31.55
40 29.88888888888889
50 27.866666666666667
60 6.666666666666667
70 19.181818181818183
80 13.0
90 23.666666666666668
100 39.111111111111114


## Mean of Sachin's scores when Rahul scored less than 10

In [74]:
players_data = cric_data[:,0:3]

In [81]:
players_cum = np.cumsum(players_data[:,1],axis=0)/denom

In [83]:
condition = players_cum[players_data[:,2]<10]
print(condition)

[40.64285714 38.86666667 34.52941176 32.61111111 31.95238095 35.29166667
 35.55555556 34.28571429 34.9        39.0625     38.55       38.26829268
 38.57142857 38.09302326 41.68       39.34545455 39.77777778 40.
 40.6969697  40.29850746 40.57971014 39.88888889 39.6375     39.20987654
 37.96428571 38.01162791 39.34065934 39.92391304 39.49462366 40.81052632
 40.0990099  38.9537037  39.08256881 38.52252252 38.90178571 39.02631579
 40.01709402 39.75423729 39.38211382 39.93700787 39.55384615 39.34351145
 39.15037594 39.32592593 39.36029412 39.67153285 39.38405797 39.42857143
 39.98675497 40.14473684 40.16339869 40.37012987 40.65294118 40.69005848
 40.35260116 40.32183908 40.59428571 41.0726257  41.04972376 41.42857143
 42.         41.80978261 41.17021277 40.98963731 40.82178218 40.62068966
 40.38888889 40.21198157 39.875      39.87555556]


## Find mean for Sachin's scores based on which quartile India falls in

In [90]:
quartiles = np.percentile(cric_data[:,3],[25,50,75])
print(quartiles)

[175. 216. 273.]


In [97]:
sachin_cum = np.cumsum(sachin_scores)/denom
#sachin_cum = np.hstack((cric_data[:,0],sachin_cum))

In [112]:
for i in range(0,3):
    print("mean of scores in the Q",i+1,"quartile\n",sachin_cum[cric_data[:,3]<quartiles[i]].reshape(-1,1))

mean of scores in the Q 1 quartile
 [[47.36363636]
 [38.86666667]
 [32.61111111]
 [31.95238095]
 [34.42307692]
 [35.55555556]
 [34.28571429]
 [34.44827586]
 [34.9       ]
 [35.62162162]
 [38.84615385]
 [41.68      ]
 [41.39215686]
 [39.34545455]
 [40.38333333]
 [40.6969697 ]
 [40.21428571]
 [40.13924051]
 [39.20987654]
 [38.82926829]
 [38.57954545]
 [39.49462366]
 [40.0990099 ]
 [39.71568627]
 [39.33009709]
 [38.52252252]
 [38.90178571]
 [39.38211382]
 [39.96825397]
 [39.93700787]
 [39.34351145]
 [39.18939394]
 [39.38405797]
 [39.42857143]
 [39.22758621]
 [39.7388535 ]
 [40.35185185]
 [40.3313253 ]
 [40.69005848]
 [40.35260116]
 [40.32183908]
 [41.04972376]
 [41.80978261]
 [41.54301075]
 [41.3315508 ]
 [41.17021277]
 [41.04232804]
 [40.69109948]
 [40.46      ]
 [40.62068966]
 [40.61904762]
 [40.44651163]
 [40.21198157]
 [39.83257919]
 [39.93273543]]
mean of scores in the Q 2 quartile
 [[55.5       ]
 [47.36363636]
 [38.86666667]
 [34.52941176]
 [32.61111111]
 [32.        ]
 [31.9523809

## Who scored more in every match?

In [44]:
both = cric_data[:,1:3]
who = np.argmax(both,axis=1)
print(who)
print("Rahul Dravid scored greater than Sachin in",np.sum(who)/225*100,"% matches")

[0 1 1 0 0 1 1 0 1 0 1 1 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1 1
 0 1 0 0 0 0 1 0 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 1 0 1 0 0 0 0 1 0 1 1 0 0 1
 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 0 1 1 0 0 0
 0 1 0 1 0 0 0 1 0 1 0 0 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 1
 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 0 0 1 0 1 1 0 0 1 0 0 0 0 1 0 1 1 0 0 0 0 1
 1 1 0 1 1 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 1 1 1 0 0 0 1 1 0 1 0 1 1 1 1 0 0
 1 0 0]
Rahul Dravid scored greater than Sachin in 47.11111111111111 % matches


In [45]:
np.where(who==0,"Sachin","Rahul")

array(['Sachin', 'Rahul', 'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin',
       'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin'

## How many more runs does Sachin score on average after scoring x runs

In [48]:
np.amax(sachin_scores)

186.0

In [50]:
check = np.arange(0,187)
#print(check)

In [51]:
check = check.reshape(-1,1)

In [55]:
index = sachin_scores >= check

In [57]:
for i in range(index.shape[0]):
    print(check[i],np.mean(sachin_scores[index[i]])-check[i])

[0] [39.87555556]
[1] [42.34299517]
[2] [43.94871795]
[3] [45.32432432]
[4] [45.32596685]
[5] [45.61363636]
[6] [45.6744186]
[7] [45.76190476]
[8] [46.16564417]
[9] [47.23717949]
[10] [47.48026316]
[11] [47.11333333]
[12] [47.40410959]
[13] [47.73943662]
[14] [47.07801418]
[15] [47.45255474]
[16] [46.80147059]
[17] [47.21969697]
[18] [47.31782946]
[19] [47.44444444]
[20] [46.824]
[21] [46.2016129]
[22] [45.95901639]
[23] [45.33884298]
[24] [45.10084034]
[25] [44.10084034]
[26] [43.85470085]
[27] [43.23275862]
[28] [44.18018018]
[29] [45.26415094]
[30] [45.13461538]
[31] [44.57281553]
[32] [44.00980392]
[33] [44.34343434]
[34] [43.79591837]
[35] [43.24742268]
[36] [43.62765957]
[37] [43.09677419]
[38] [43.53333333]
[39] [43.52272727]
[40] [44.05882353]
[41] [44.12048193]
[42] [44.20987654]
[43] [43.20987654]
[44] [42.75]
[45] [43.41558442]
[46] [44.79452055]
[47] [44.41666667]
[48] [44.68571429]
[49] [44.33333333]
[50] [43.98529412]
[51] [43.64179104]
[52] [43.3030303]
[53] [42.96923077

## How many matches did Sachin take to score first 1000 runs, next 1000 runs

In [3]:
sachin_scores = cric_data[:,1]

In [4]:
sachin_scores

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
         4.,   7.,  37.,  14.,   0.,   4.,   0.,  21.,   1.,  62.,   0.,
       138.,  38.,   2.,  46.,  65.,   0.,  39.,  48., 141.,  62.,  12.,
         1.,  41.,  11.,   3., 186.,  11.,  27.,  27.,  51.,  18.,  32.,
       146.,   5.,  45., 141.,  12.,  65.,  27.,   7.,  16.,   2.,  28.,
         6., 123., 120.,   7.,   3.,   0.,  81.,   2.,  54., 122.,   4.,
        14.,   0., 100.,  15.,   0.,  57.,  99.,  37.,  38.,  32.,  21.,
        32.,  40.,   0.,   5.,   8.,   5.,   0.,  50.,  30.,  37.,  89.,
         4.,  98.,  83.,  93.,   0.,  52., 152.,   1.,   8.,  93.,  45.,
        26.,   0.,   1.,   0.,  16.,  47.,  89.,   3.,   1.,  53.,  16.,
         0.,  81.,  14.,  78.,   6., 105., 122.,   9.,   8.,  28.,  35.,
        69.,  13.,  97.,  93.,   2.,  36.,  39.,   2.,  29.,  12.,  19.,
        34.,   2., 100.,  44.,  82.,   0.,  79.,   6.,   9.,   8.,  23.,
        93.,  35.,  63.,  74.,   8., 117.,  39.,  4

In [5]:
cum = np.cumsum(sachin_scores)

In [6]:
cum

array([ 100.,  111.,  119.,  190.,  294.,  312.,  320.,  406.,  418.,
        503.,  521.,  525.,  532.,  569.,  583.,  583.,  587.,  587.,
        608.,  609.,  671.,  671.,  809.,  847.,  849.,  895.,  960.,
        960.,  999., 1047., 1188., 1250., 1262., 1263., 1304., 1315.,
       1318., 1504., 1515., 1542., 1569., 1620., 1638., 1670., 1816.,
       1821., 1866., 2007., 2019., 2084., 2111., 2118., 2134., 2136.,
       2164., 2170., 2293., 2413., 2420., 2423., 2423., 2504., 2506.,
       2560., 2682., 2686., 2700., 2700., 2800., 2815., 2815., 2872.,
       2971., 3008., 3046., 3078., 3099., 3131., 3171., 3171., 3176.,
       3184., 3189., 3189., 3239., 3269., 3306., 3395., 3399., 3497.,
       3580., 3673., 3673., 3725., 3877., 3878., 3886., 3979., 4024.,
       4050., 4050., 4051., 4051., 4067., 4114., 4203., 4206., 4207.,
       4260., 4276., 4276., 4357., 4371., 4449., 4455., 4560., 4682.,
       4691., 4699., 4727., 4762., 4831., 4844., 4941., 5034., 5036.,
       5072., 5111.,

In [12]:
np.histogram(cum,[0,1000,2000,3000,4000,5000,6000,7000,8000,9000])

(array([29, 18, 26, 25, 26, 26, 23, 22, 30]),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))

In [11]:
np.histogram?